# Generated by Django 5.2.7 on 2025-10-31 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(blank=True, max_length=128)),
                ('driver_signature', models.TextField(blank=True)),
                ('co_driver_name', models.CharField(blank=True, max_length=128)),
                ('home_terminal', models.CharField(blank=True, max_length=128)),
                ('carrier_name', models.CharField(blank=True, max_length=128)),
                ('tractor_number', models.CharField(blank=True, max_length=64)),
                ('trailer_numbers', models.JSONField(default=list)),
                ('shipper', models.CharField(blank=True, max_length=128)),
                ('commodity', models.CharField(blank=True, max_length=128)),
                ('shipping_doc_numbers', models.JSONField(default=list)),
                ('total_miles_driven', models.FloatField(default=0.0)),
                ('total_truck_mileage', models.FloatField(default=0.0)),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_berth_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_not_driving_hours', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.JSONField(default=list)),
                ('total_distance', models.FloatField(default=0.0)),
                ('estimated_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty Not Driving')], max_length=32)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('location', models.JSONField(default=dict)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('miles_driven', models.FloatField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.dailylog')),
            ],
            options={
                'ordering': ['sequence', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('admin', 'Admin')], default='driver', max_length=16)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('cdl_number', models.CharField(blank=True, max_length=64)),
                ('home_terminal', models.CharField(blank=True, max_length=128)),
                ('carrier_name', models.CharField(blank=True, max_length=128)),
                ('carrier_address', models.CharField(blank=True, max_length=256)),
                ('signature', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fuel', 'Fuel'), ('30min_break', '30 Minute Break'), ('10hr_rest', '10 Hour Rest'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=32)),
                ('location', models.JSONField(default=dict)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('miles_from_start', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.route')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planning', max_length=32)),
                ('current_location', models.JSONField(default=dict)),
                ('pickup_location', models.JSONField(default=dict)),
                ('dropoff_location', models.JSONField(default=dict)),
                ('current_cycle_hours', models.FloatField(default=0.0)),
                ('total_distance', models.FloatField(default=0.0)),
                ('estimated_duration', models.FloatField(default=0.0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.driver')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='api.trip'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'date')},
        ),
    ]
