# Generated by Django 5.2.7 on 2025-10-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_location',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
