# Generated by Django 5.2.7 on 2025-10-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_end_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
